### PR TITLE
fixes for "cost-optimized" srTakeover/srCostOptMemConfig hook

### PR DESCRIPTION
**Pull request by yeoldegrove**
This PR:

- fixes a not working import of `dbapi` in https://github.com/SUSE/ha-sap-terraform-deployments/issues/703

- removes the installation and extraction of all `hdbcli` files in the `/hana/shared/srHook` directory
  - I could not find a reference to them anywhere else.

- removes the python shebang
  - no SAP reference implementation (except https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-CostOpt-12/#_srcostoptmemconfig) mentions it.
  - the SUSE SAPHanaSR hook also does not have it
  - HANA ships python2/3 so this might be future proof

- fixes execution order of srTakeover/srCostOptMemConfig hook
  - has to be a different value than SAPHanaSR hook

- renames and updates hook `srTakeover` to `srCostOptMemConfig`
  - according to latest documentation https://documentation.suse.com/sbp/all/single-html/SLES4SAP-hana-sr-guide-CostOpt-12/#id-1.9.10.3

Installation of a "cost-optimized" HANA 2.0 SPS03 on a SLES 15.2 on azure worked fine for me after these changes.
The Hook is called successfully:
```
nameserver_vmhana02.30001.000.trc:[22103]{-1}[-1/-1] 2021-06-08 15:56:55.581892 i ha_dr_provider   HADRProviderManager.cpp(00070) : loading HA/DR Provider 'srCostOptMemConfig' from /hana/shared/srHook
nameserver_vmhana02.30001.000.trc:[22161]{-1}[-1/-1] 2021-06-08 15:56:56.375058 i ha_dr_provider   PythonProxyImpl.cpp(00886) : calling HA/DR provider srCostOptMemConfig.startup(hostname=vmhana02, storage_partition=1, system_replication_mode=sync)
nameserver_vmhana02.30001.000.trc:[22194]{-1}[-1/-1] 2021-06-08 15:57:02.493514 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30001, service=nameserver, state=starting, previous status=unknown, daemonActiveStatus=starting, databaseId=1, databaseName=SYSTEMDB, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22194]{-1}[-1/-1] 2021-06-08 15:57:02.497478 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30001, service=nameserver, state=yes, previous status=starting, daemonActiveStatus=starting, databaseId=1, databaseName=SYSTEMDB, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22195]{-1}[-1/-1] 2021-06-08 15:57:02.504535 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30001, service=nameserver, state=yes, previous status=yes, daemonActiveStatus=starting, databaseId=1, databaseName=SYSTEMDB, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22123]{-1}[-1/-1] 2021-06-08 15:57:04.817521 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30010, service=compileserver, state=starting, previous status=no, daemonActiveStatus=starting
nameserver_vmhana02.30001.000.trc:[22123]{-1}[-1/-1] 2021-06-08 15:57:04.837831 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30010, service=compileserver, state=yes, previous status=starting, daemonActiveStatus=starting
nameserver_vmhana02.30001.000.trc:[22237]{-1}[-1/-1] 2021-06-08 15:57:05.118364 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30002, service=preprocessor, state=starting, previous status=no, daemonActiveStatus=starting
nameserver_vmhana02.30001.000.trc:[22237]{-1}[-1/-1] 2021-06-08 15:57:05.126090 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30002, service=preprocessor, state=yes, previous status=starting, daemonActiveStatus=starting
nameserver_vmhana02.30001.000.trc:[22250]{-1}[-1/-1] 2021-06-08 15:57:10.039442 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30003, service=indexserver, state=starting, previous status=no, daemonActiveStatus=starting, databaseId=3, databaseName=PRD, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22458]{-1}[-1/-1] 2021-06-08 15:57:10.098597 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30007, service=xsengine, state=starting, previous status=no, daemonActiveStatus=starting, databaseId=3, databaseName=PRD, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22508]{-1}[-1/-1] 2021-06-08 15:57:17.722198 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30007, service=xsengine, state=yes, previous status=starting, daemonActiveStatus=starting, databaseId=3, databaseName=PRD, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22505]{-1}[-1/-1] 2021-06-08 15:57:29.920176 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30003, service=indexserver, state=yes, previous status=starting, daemonActiveStatus=starting, databaseId=3, databaseName=PRD, databaseActiveStatus=yes
nameserver_vmhana02.30001.000.trc:[22195]{-1}[-1/-1] 2021-06-08 15:57:31.487960 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30006, service=webdispatcher, state=starting, previous status=no, daemonActiveStatus=starting
nameserver_vmhana02.30001.000.trc:[22509]{-1}[-1/-1] 2021-06-08 15:57:33.758470 i ha_dr_provider   PythonProxyImpl.cpp(01217) : calling HA/DR provider srCostOptMemConfig.srServiceStateChanged(hostname=vmhana02, port=30006, service=webdispatcher, state=yes, previous status=starting, daemonActiveStatus=starting
```

There is also a test rpm available here:

https://build.opensuse.org/package/show/home:waldt:branches:network:ha-clustering:sap-deployments:devel/saphanabootstrap-formula

Which can be used like this:
```
e.g.:
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/home:/waldt:/branches:/network:/ha-clustering:/sap-deployments:/devel/SLE_15_SP2/"
or:
ha_sap_deployment_repo = "https://download.opensuse.org/repositories/home:/waldt:/branches:/network:/ha-clustering:/sap-deployments:/devel/SLE_15_SP3/"
```

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
@yeoldegrove Approved from my side.

Anyway, I would like to get the opinion from @pirat013 or @fmherschel before merging.

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@yeoldegrove I forgot to mention. Could you add an entry in the `saphanabootstrap-formula.changes` file, mentioning the applied fix? (you could use `osc vc`).
You don't need to increase the version, I will do it myself when we ship the formula, as we will need a bgz ticket that we don't have right now.

**Comment by pirat013** [comment]
@yeoldegrove Thanks for all the work. I'll leave the decision to the HA team. They  should decide regarding the documentation change. Only one comment the combination of SAP HANA and the OS version is not supported. HANA 2.0 SPS3 is out of support since Jun 2020. For SLES 15 SP3 HANA 2.0 SPS5 rev 55 or 56 will be validated.

**Comment by yeoldegrove** [comment]
> @yeoldegrove I forgot to mention. Could you add an entry in the `saphanabootstrap-formula.changes` file, mentioning the applied fix? (you could use `osc vc`).
> You don't need to increase the version, I will do it myself when we ship the formula, as we will need a bgz ticket that we don't have right now.

done

**Review by arbulu89 — APPROVED** [review]
@yeoldegrove Nice!
Let's wait for some time until getting some feedback about the document.
In any case the changes look good so we will be able to merge

**Comment by arbulu89** [comment]
Merged since @fmherschel gave green light

**Pull request merged**
