### PR TITLE
Fix pillar.example file location in package

### PR DESCRIPTION
**Pull request by Simranpal**
Changing the location of `pillar.example` file in package,
and fix typo in readme

### CODE REVIEW

**Comment by arbulu89** [comment]
@Simranpal How is this PR? I thought we were going to add the `pillar.example` as documentation. So it should go in the `doc` entry, and not in metadata folder.

**Comment by Simranpal** [comment]
> @Simranpal How is this PR? I thought we were going to add the `pillar.example` as documentation. So it should go in the `doc` entry, and not in metadata folder.

@arbulu89 following the other salt formulas , I placed the `pillar.example` in metadata folder. There is no `doc` folder created in other formulas I see.
https://github.com/SUSE/salt-formulas

**Comment by arbulu89** [comment]
> > @Simranpal How is this PR? I thought we were going to add the `pillar.example` as documentation. So it should go in the `doc` entry, and not in metadata folder.
> 
> @arbulu89 following the other salt formulas , I placed the `pillar.example` in metadata folder. There is no `doc` folder created in other formulas I see.
> https://github.com/SUSE/salt-formulas

I don't see any documentation about having the `pillar.example` in the metadata folder, but if everyone else do so...
The `doc` folder is created for all the installed packages (check the `doc` keyword in the spec file).
In SUSE, this folder links to `/usr/share/doc/packages`

**Review by arbulu89 — APPROVED** [review]

**Review by MalloZup — CHANGES_REQUESTED** [review]
I'm ok with this. Only can we document this somewhere? 

Can you create maybe some entry on confluence?

**Review by MalloZup — APPROVED** [review]

**Pull request merged**
