### PR TITLE
Choose shaptools py2 or py3 accordingly with the OS version.

### PR DESCRIPTION
**Pull request by diegoakechi**
SLE-15 has adopted python3 while SLE-12 still uses python2. So, the formula needs to install the correct python version shaptools package.

### CODE REVIEW

**Comment by juadk** [comment]
Tested and it's works, but my python2 dependency problem seems to be elsewhere...

**Comment by arbulu89** [comment]
@diegoakechi I'm not sure if this solves all the use cases. What about the cases where we need to install python2-shaptools (salt using python2 but SLES version is 15). Is this case possible?

Can we detect current python version during salt execution and use that to choose between versions?

**Comment by diegoakechi** [comment]
@arbulu89 Nice work. Much better ;)

**Comment by juadk** [comment]
@arbulu89 Great, this will fix my last salt issue!

**Pull request merged**
