### PR TITLE
implement minimal validation on travis

### PR DESCRIPTION
**Pull request by MalloZup**
# description:

validate salt-state in formula, so we can prevent some typos etc.

It is experimental for moment

### CODE REVIEW

**Comment by MalloZup** [comment]
we have 2 issues here:

1) travis doesn't push the status of the validation to the pr ( somehow is strange)

2) the validation doesn't validate all states somehow. 

now i can read grains correctly but we might need to pass some grains. We don't validate much

For setting some grains needed, we can do as following: 
https://github.com/uyuni-project/sumaform/blob/master/.ci-travis/salt-server-validation#L4

**Comment by MalloZup** [comment]
https://travis-ci.org/SUSE/saphanabootstrap-formula/jobs/555864611#L650

**Comment by MalloZup** [comment]
@arbulu89 added host hana01 and hana02. Looks good to me to be merged

**Comment by arbulu89** [comment]
Cost optimized added and working properly!

**Pull request merged**
